---
title: "DANL 320 CW5"
editor: visual
---

```{r}
library(tidyverse)
library(broom)
library(stargazer)
library(margins)
library(yardstick)
library(WVPlots)
library(pROC)
library(glmnet)
library(gamlr)
```

```{r}
df <- read_csv('https://bcdanl.github.io/data/car-data.csv')

df |> 
  rmarkdown::paged_table()
```

# Question 1

```{r}
df |> 
  count(buying)
df |> 
  count(maint)
df |> 
  count(persons)
df |> 
  count(lug_boot)
df |> 
  count(safety)
```

```{r}
set.seed(14454)
df <- df |> 
  mutate(rnd = runif(n())) |> 
  mutate(buying = factor(buying),
         buying = fct_relevel(buying, "low"),
         maint = factor(maint),
         maint = fct_relevel(maint, "low"),
         persons = factor(persons),
         persons = fct_relevel(persons, "2"),
         lug_boot = factor(lug_boot),
         lug_boot = fct_relevel(lug_boot, "small"),
         safety = factor(safety),
         safety = fct_relevel(safety, "low"))

dtrain <- df |> 
  filter(rnd > .3)
dtest <- df |> 
  filter(rnd <= .3)

```

# Question 2

```{r}
model <- glm(
  fail ~ buying + maint + persons + lug_boot + safety,
  data = dtrain,
  family = binomial(link = "logit")
)
```

# 
